### ISSUE TITLE
Module 3 Exercise 3 StorageAccountSharedKeyCredential not needed and breaks app.

### ISSUE THREAD

**Issue by cowhitley** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#448]
# Module: 03
#### Step: 01

Description of issue

The StorageSharedKeyCredential causes an error when running the application and is not needed. The BlobServiceClient can accept just the connection string as parameter to be instantiated.

dotnet --version: 6.0.201

Error when running the application:
Unhandled exception. System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
   at System.Convert.FromBase64_ComputeResultLength(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at Azure.Storage.StorageSharedKeyCredential.SetAccountKey(String accountKey)
   at Azure.Storage.StorageSharedKeyCredential..ctor(String accountName, String accountKey)
   at Program.Main(String[] args) in C:\Users\<username>\source\repos\allfiles\Labs\03\Starter\BlobManager\Program.cs:line 15
   at Program.<Main>(String[] args) 

By commenting out the line building the accountCredentials variable and then just passing along the storageAccountKey as the parameter to the BlobServiceClient it works as expected.

![image](https://user-images.githubusercontent.com/49291217/159127921-f92882cc-9ebd-4b8e-a4f7-f21e78e290cc.png)

**Comment by WigF1** [comment]
This issue occurs when students copy the connection string value instead of the storage key value.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review did not experience this issue.

**Comment by JeffKoMS** [comment]
Closing, see comment above for resolution.
